### ISSUE TITLE
プロセス数の上限設定を考慮するか？

### ISSUE THREAD

**Issue by Hyu-waseda** [kkaneko-42/minishell#108]
ワカモレでは恐らく709が上限

c1r22s10% limit 
cputime         unlimited
filesize        unlimited
datasize        unlimited
stacksize       8MB
coredumpsize    0kB
addressspace    unlimited
memorylocked    unlimited
maxproc         709
descriptors     256

**Comment by kkaneko-42** [comment]
後ほど、bashにパイプ710個突っ込んで試してみます。

**Comment by kkaneko-42** [comment]
確認したら、すでに対応されていました。
以下のpythonを実行しました。

import os
 
cmd_name = "echo hoge "
nb_pipe = 800
 
for i in range(nb_pipe):
    print(format(i) + "/" + format(nb_pipe))
    cmd_name += "| cat "
 
os.system(cmd_name)
